# This script produces summary statistics for the testing data

#!/usr/bin/env Rscript
library(dplyr)
library(readr)
library(tidyr)

cat("Running unbiased summary for TEST data...\n")

# Uses files generated by testing_performance.R
test_files <- list(
  list(name="31_contexts", file="test_r2_existing_models_long.csv"), 
  list(name="30_contexts", file="test_r2_no_nkp_long.csv"),
  list(name="29_contexts", file="test_r2_no_nkp_nkcd56_long.csv"),
  list(name="28_contexts", file="test_r2_no_all_nk_long.csv")
)

all_test_summaries <- list()

for (run in test_files) {
  if (!file.exists(run$file)) {
    cat(sprintf("  Skipping %s: file %s not found.\n", run$name, run$file))
    next
  }
  
  df <- read_csv(run$file, show_col_types = FALSE)
  
  # Correction for NA dropping, instead of dropping it becomes 0
  
  df_clean <- df %>%
    mutate(
      r2 = ifelse(is.na(r2) | r2 < 0, 0, r2),
      
      # Fixing weird naming from other files
      
      method = case_when(
        method %in% c("cbc", "Single_Context")   ~ "Context_by_Context",
        method %in% c("full", "Full_Model")       ~ "Full_Model",
        method %in% c("shared", "Shared_Only")   ~ "Shared_Only",
        method %in% c("specific", "Specific_Only") ~ "Specific_Only",
        TRUE ~ method
      )
    )
  
  # Group by method so all four models are summarized 
  
  summary_stats <- df_clean %>%
    group_by(method) %>%
    summarise(
      n_genes         = n(),
      mean_test_r2    = mean(r2),
      median_test_r2  = median(r2),
      pct_test_r2_gt0 = mean(r2 > 0) * 100,
      .groups         = "drop"
    ) %>%
    mutate(run_type = run$name)
  
  all_test_summaries[[run$name]] <- summary_stats
}

# Make final output and .csv

if (length(all_test_summaries) > 0) {
  final_test_df <- bind_rows(all_test_summaries) %>%
    select(run_type, method, n_genes, mean_test_r2, median_test_r2, pct_test_r2_gt0) %>%
    mutate(run_type = factor(run_type, levels = c("31_contexts", "30_contexts", "29_contexts", "28_contexts"))) %>%
    arrange(run_type, method)
  
  print(as_tibble(final_test_df))
  write_csv(final_test_df, "summary_stats_testing_UNBIASED_F.csv")
  cat("\nSaved to summary_stats_testing_UNBIASED_F.csv\n")
} else {
  cat("No test summary files processed. Please check the filenames output by testing_performance.R\n")
}
